#!/usr/bin/env bash

case $DOCKER_TAG in
	stable)
		DEFAULT=stable
		;;

	beta)
		DEFAULT=beta
		;;

	nightly)
		DEFAULT=nightly
		;;

	all)
		TOOLCHAINS="stable beta nightly"
		;;

	*)
		>&2 echo "Unknown tag."
		exit 1
		;;
esac

docker build . \
	--build-arg RUSTUP_DEFAULT="${DEFAULT:-stable}" \
	--build-arg RUSTUP_TOOLCHAINS="$TOOLCHAINS" \
	--build-arg RUSTUP_TARGETS="$TARGETS"
